models/Transfer.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "transfer".
 *
 * @property integer $id
 * @property integer $from_user_id
 * @property integer $to_user_id
 * @property string $amount
 * @property integer $status
 * @property integer $protection_code
 */
class Transfer extends \yii\db\ActiveRecord
{

    public $user_name;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transfer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['from_user_id', 'to_user_id', 'amount', 'status'], 'required'],
            [['from_user_id', 'to_user_id', 'status', 'protection_code'], 'integer'],
            [['amount'], 'number'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'from_user_id' => 'From User ID',
            'to_user_id' => 'To User ID',
            'amount' => 'Amount',
            'status' => 'Status',
            'protection_code' => 'Protection Code',
        ];
    }

    public function getStatusName(){
      return $this->hasOne(Status::className(), ['id' => 'status']);
    }

    public function getUserFrom(){
      return $this->hasOne(User::className(), ['id' => 'from_user_id']);
    }

    public function getUserTo(){
      return $this->hasOne(User::className(), ['id' => 'to_user_id']);
    }

}

controllers/TransferController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Transfer;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ForbiddenHttpException;
use yii\filters\VerbFilter;
use app\models\User;

/**
 * TransferController implements the CRUD actions for Transfer model.
 */
class TransferController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['return', 'protection', 'index', 'view', 'create', 'admin'],
                'rules' => [
                    [
                        'actions' => ['return', 'protection', 'index', 'view', 'create', 'admin'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'return' => ['post'],
                ],
            ],
        ];
    }
    /**
     * Lists all Transfer models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Transfer::find()
                ->where(['to_user_id' => Yii::$app->user->identity->id])
                ->orWhere(['from_user_id' => Yii::$app->user->identity->id]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Transfer models.
     * @return mixed
     */
    public function actionAdmin()
    {
        if (Yii::$app->user->identity->username == 'admin'){
            $dataProvider = new ActiveDataProvider([
                'query' => Transfer::find(),
            ]);

            return $this->render('admin', [
                'dataProvider' => $dataProvider,
            ]);
        }
        else
        {
            throw new ForbiddenHttpException('You are not allowed to access this page.');
        }
    }

    /**
     * Displays a single Transfer model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Transfer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Transfer();

        if ($model->load(Yii::$app->request->post())) {
            $model->from_user_id = Yii::$app->user->identity->id;
            $model->to_user_id = User::getUserIdByUsername(Yii::$app->request->post('Transfer')['user_name']);

            if ($model->protection_code == '')
            {
                $user = User::findIdentity($model->to_user_id);
                $user->balance = $user->balance + $model->amount;

                $intiator = User::findIdentity($model->from_user_id);
                $intiator->balance = $intiator->balance - $model->amount;

                $model->status = 1;

                $user->save();
                $intiator->save();
                $model->save();
            }
            elseif ($model->protection_code != '')
            {
                $model->status = 2;
                $model->save();
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Transfer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionProtection($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->post('Transfer')['protection_code'] != ''
            && $model->status == 2
            && $model->to_user_id == Yii::$app->user->identity->id
        ) {
            if ($model->protection_code == Yii::$app->request->post('Transfer')['protection_code'])
            {
                $user = User::findIdentity($model->to_user_id);
                $user->balance = $user->balance + $model->amount;

                $intiator = User::findIdentity($model->from_user_id);
                $intiator->balance = $intiator->balance - $model->amount;

                $model->status = 1;

                $user->save();
                $intiator->save();
                $model->save();
                \Yii::$app->getSession()->setFlash('success', 'Code ok! Transfer succeeded');
            }
            else
            {
                \Yii::$app->getSession()->setFlash('error', 'Code not ok!');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $model->protection_code = '';
            return $this->render('protection', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Transfer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionReturn($id)
    {
        $model = $this->findModel($id);

        if ($model->status == 1 && $model->to_user_id == Yii::$app->user->identity->id){
            $user = User::findIdentity($model->to_user_id);
            $user->balance = $user->balance - $model->amount;

            $intiator = User::findIdentity($model->from_user_id);
            $intiator->balance = $intiator->balance + $model->amount;

            $model->status = 3;

            $user->save();
            $intiator->save();
            $model->save();

            \Yii::$app->getSession()->setFlash('success', 'Transfer returned');
        }

        return $this->redirect(['view', 'id' => $model->id]);
    }

    /**
     * Finds the Transfer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Transfer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Transfer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/transfer/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Transfer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="transfer-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_name')->textInput() ?>

    <?= $form->field($model, 'amount')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'protection_code')->textInput()->label('Protection Code <small>(enter 4-digit code to make this transfer protected)</small>') ?>

    <div class="form-group">
        <?= Html::submitButton('Create', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/transfer/_form_protection.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Transfer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="protection-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'protection_code')->textInput()->label('Protection Code <small>(enter 4-digit code to recive this transfer)</small>') ?>

    <div class="form-group">
        <?= Html::submitButton('Receive', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/transfer/admin.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'All Transfers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transfer-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Transfer', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            [
                'label' => 'From',
                'value' => 'userFrom.username',
            ],
            [
                'label' => 'To',
                'value' => 'userTo.username',
            ],
            'amount',
            [
                'label' => 'Status',
                'value' => 'statusName.status_name',
            ],
            'protection_code',
        ],
    ]); ?>
</div>

views/transfer/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Transfer */

$this->title = 'Create Transfer';
$this->params['breadcrumbs'][] = ['label' => 'Transfers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transfer-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/transfer/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\grid\ActionColumn;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Transfers';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transfer-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Transfer', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            [
                'label' => 'From',
                'value' => 'userFrom.username',
            ],
            [
                'label' => 'To',
                'value' => 'userTo.username',
            ],
            'amount',
            [
                'label' => 'Status',
                'value' => 'statusName.status_name',
            ],
            // 'protection_code',

            ['class' => ActionColumn::className(),
            'template' => '{view} {protection} {return}',
            'buttons' => [

                'protection' => function ($url, $model, $key) {
                    if ($model->status == 2 && $model->to_user_id == Yii::$app->user->identity->id)
                    {
                        return Html::a('<span class="glyphicon glyphicon-exclamation-sign"></span>',
                            Url::to(['/transfer/protection', 'id' => $model->id]),
                        [
                            'title' => Yii::t('yii', 'Protection'),
                            'aria-label' => Yii::t('yii', 'Protection'),
                            'data-pjax' => '0',
                        ]
                        );
                    }
                },

                'return' => function ($url, $model, $key) {
                    if ($model->status == 1 && $model->to_user_id == Yii::$app->user->identity->id)
                    {
                        return Html::a('<span class="glyphicon glyphicon-share-alt"></span>',
                            Url::to(['/transfer/return', 'id' => $model->id]),
                        [
                            'title' => Yii::t('yii', 'Return'),
                            'data-confirm' => 'Are you sure you want to return this transfer?',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                        ]);
                    }
                },
            ],
            ],

        ],
    ]); ?>
</div>

views/transfer/protection.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Transfer */

$this->title = 'Enter protection code for: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Transfers', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Protection';
?>
<div class="transfer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_protection', [
        'model' => $model,
    ]) ?>

</div>

views/transfer/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Transfer */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Transfers', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="transfer-view">

    <h1><?= Html::encode($this->title) ?></h1>

        <?php if(Yii::$app->session->getFlash('error')): ?>
            <div class="alert alert-danger" role="alert">
                <?= Yii::$app->session->getFlash('error'); ?>
            </div>
        <?php endif; ?>

        <?php if(Yii::$app->session->getFlash('success')): ?>
            <div class="alert alert-success" role="success">
                <?= Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif; ?>

    <p>


        <?php if($model->status == 2 && $model->to_user_id == Yii::$app->user->identity->id){
            echo Html::a('Enter Protection Code', ['protection', 'id' => $model->id], ['class' => 'btn btn-primary']);
        }
        ?>


        <?php if($model->status == 1 && $model->to_user_id == Yii::$app->user->identity->id){
            echo Html::a('Return', ['return', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to return this transfer?',
                    'method' => 'post',
                ],
            ]);
        }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'userFrom.username',
            'userTo.username',
            'amount',
            'statusName.status_name',
            // 'protection_code',
        ],
    ]) ?>

</div>